[project]
name = "simple-rl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gymnasium>=1.2.2",
    "matplotlib>=3.10.8",
    "numpy>=2.3.5",
    "pygame>=2.6.1",
    "tk>=0.1.0",
    "tqdm>=4.67.1",
]
